// Generated by CoffeeScript 1.3.3
(function() {
  var context, newGain, noise, noiseNode, started;

  context = new webkitAudioContext();

  noise = new NoiseGen(context, "white");

  noiseNode = noise.getNode();

  newGain = context.createGain();

  noiseNode.connect(newGain);

  newGain.connect(context.destination);

  started = false;

  $(".btn").click(function(e) {
    if (started === false) {
      noise.start();
      return started = true;
    }
  });

  $("#btn-white").click(function() {
    return noise.setNoiseType("white");
  });

  $("#btn-brown").click(function() {
    return noise.setNoiseType("brown");
  });

  $("#btn-pink").click(function() {
    return noise.setNoiseType("pink");
  });

  $("#sldr-volume").change(function(e) {
    var volume;
    volume = e.target.value;
    return noise.setVolume(volume / 100);
  });

}).call(this);
